In [77]:
#Import Libraries
import pandas as pd
import re
import numpy as np
import datetime
import seaborn as sns
import matplotlib.pyplot as plt
car_data= pd.read_csv("/content/train.csv")
car_data.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
1,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,13 km/kg,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
2,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,3.50

In [78]:
car_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5847 entries, 0 to 5846
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         5847 non-null   int64
 1   Name               5847 non-null   object
 2   Location           5847 non-null   object
 3   Year               5847 non-null   int64
 4   Kilometers_Driven  5847 non-null   int64
 5   Fuel_Type          5847 non-null   object
 6   Transmission       5847 non-null   object
 7   Owner_Type         5847 non-null   object
 8   Mileage            5845 non-null   object
 9   Engine             5811 non-null   object
 10  Power              5811 non-null   object
 11  Seats              5809 non-null   float64
 12  New_Price          815 non-null    object
 13  Price              5847 non-null   float64
dtypes: float64(2), int64(3), object(9)
memory usage: 639.6+ KB

# Data Pre-processing

Look for the missing values in all the columns and either impute them (replace with mean, median, or mode) or drop them.
Justify your action for this task.

In [79]:
#Check for null values
car_data.isnull().sum()

Unnamed: 0              0
Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 36
Power                  36
Seats                  38
New_Price            5032
Price                   0
dtype: int64

In [33]:
mean_seats = car_data['Seats'].mean()

# Fill missing values in the "Seats" column with the mean
car_data['Seats'].fillna(mean_seats, inplace=True)

car_data.head(5)

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
1,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,13 km/kg,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
2,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,3.50

In [34]:
#Check for null values
car_data.isnull().sum()

Unnamed: 0              0
Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 36
Power                  36
Seats                   0
New_Price            5032
Price                   0
dtype: int64

Remove the units from some of the attributes and only keep the numerical values

In [82]:
#for Mileage, Engine, Power & New_Price has null values and object data datatype
# Convert the column to strings
car_data['Mileage'] = car_data['Mileage'].astype(str)
car_data['Engine'] = car_data['Engine'].astype(str)
car_data['Power'] = car_data['Power'].astype(str)
car_data['New_Price'] = car_data['New_Price'].astype(str)


# Use the .str accessor and .str.extract to extract the numeric values
car_data['Mileage'] = car_data['Mileage'].str.extract('(\d+\.\d+)', expand=False).astype(float)
car_data['Engine'] = car_data['Engine'].str.extract('(\d+\.\d+)', expand=False).astype(float)
car_data['Power'] = car_data['Power'].str.extract('(\d+\.\d+)', expand=False).astype(float)
car_data['New_Price'] = car_data['New_Price'].str.extract('(\d+\.\d+)', expand=False).astype(float)

#Functio to convert & remove units
def convert_function(text):
    if pd.notna(text):
        matches = re.findall(r'(\d+\.\d+|\d+)', str(text))
        if matches:
            return float(matches[0])
    return None

#Task for Removeing units of Mileage, Engine, Power, New_Price and extracting the Numerical values for the Coloumn
car_data["Mileage"] = car_data["Mileage"].apply(convert_function)
car_data["Engine"] = car_data["Engine"].apply(convert_function)
car_data["Power"] = car_data["Power"].apply(convert_function)
car_data["New_Price"] = car_data["New_Price"].apply(convert_function)

In [83]:
car_data.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,None,126.20,5.0,NaN,12.50
1,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,NaN,None,88.70,5.0,8.61,4.50
2,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77,None,88.76,7.0,NaN,6.00
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,None,140.80,5.0,NaN,17.74
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,23.08,None,63.10,5.0,NaN,3.50

In [87]:
#New_Price column empty values fill it up with Median
car_data['New_Price'].fillna(car_data['New_Price'].median(), inplace=True)

In [88]:
#Engine column empty values fill it up with 0

car_data['Engine'] = car_data['Engine'].fillna(0)

car_data = car_data.dropna(subset=['Engine'])

In [89]:
#Mileage, Power & Seats column empty values fill it up with mean
car_data['Mileage'].fillna(car_data['Mileage'].mean(), inplace=True)
car_data['Seats'].fillna(car_data['Seats'].mean(), inplace=True)
car_data['Power'].fillna(car_data['Power'].mean(), inplace=True)

In [90]:
car_data.isnull().sum()

Unnamed: 0           0
Name                 0
Location             0
Year                 0
Kilometers_Driven    0
Fuel_Type            0
Transmission         0
Owner_Type           0
Mileage              0
Engine               0
Power                0
Seats                0
New_Price            0
Price                0
dtype: int64

In [91]:
car_data.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.670000,0.0,126.20,5.0,11.47,12.50
1,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.159379,0.0,88.70,5.0,8.61,4.50
2,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.770000,0.0,88.76,7.0,11.47,6.00
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.200000,0.0,140.80,5.0,11.47,17.74
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,23.080000,0.0,63.10,5.0,11.47,3.50

Changing the categorical variable  into numerical one hot encoded value for Fuel type and Transmission

In [73]:
car_data = pd.get_dummies(car_data, columns=["Fuel_Type", "Transmission"])
car_data.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Current_Time,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50,8,1,0,0,0,1
1,2,Honda Jazz V,Chennai,2011,46000,First,13 km/kg,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50,12,0,0,1,0,1
2,3,Maruti Ertiga VDI,Chennai,2012,87000,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00,11,1,0,0,0,1
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74,10,1,0,0,1,0
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,3.50,10,1,0,0,0,1

Create one more feature and add this column to the dataset.
For example, you can calculate the current age of the car by subtracting “Year” value from the current year.

In [74]:
current_year = datetime.datetime.now().year
car_data['Current_Time'] = current_year - car_data['Year']

In [75]:
car_data.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Current_Time,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50,8,1,0,0,0,1
1,2,Honda Jazz V,Chennai,2011,46000,First,13 km/kg,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50,12,0,0,1,0,1
2,3,Maruti Ertiga VDI,Chennai,2012,87000,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00,11,1,0,0,0,1
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74,10,1,0,0,1,0
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,3.50,10,1,0,0,0,1

In [71]:
#Get the CSV file
car_data.to_csv("final-car-data.csv", index=False)